# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sample using Rcpp
#' @description A Gibbs sample using Rcpp
#' @param n Binomial distribution coefficient
#' @param a the Beta distribution with parameters shape1
#' @param b the Beta distribution with parameters shape2
#' @param M the Sample size
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' n <- 20
#' a <- 2
#' b <- 4
#' M <- 3500
#' randomnum.C <- gibbsC(n,a,b,M)
#' }
#' @export
gibbsC_98 <- function(n, a, b, M) {
    .Call('_StatComp21001_gibbsC_98', PACKAGE = 'StatComp21001', n, a, b, M)
}

